// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZQypm_z2K_ZPRNdeJ6qFFqUjI8-EaMEU',
    appId: '1:153311154391:web:c8e1e133d284b136ece092',
    messagingSenderId: '153311154391',
    projectId: 'blind-assist-66d0d',
    authDomain: 'blind-assist-66d0d.firebaseapp.com',
    storageBucket: 'blind-assist-66d0d.appspot.com',
    measurementId: 'G-JH5YMFS1T2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcMUJicVB1q4YKKsHhCoEAcTCMvFAZ6fE',
    appId: '1:153311154391:android:fbc6504c161c80ceece092',
    messagingSenderId: '153311154391',
    projectId: 'blind-assist-66d0d',
    storageBucket: 'blind-assist-66d0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbSMlcUCcjARwu8KgZJQ4gm3ocq13d9L8',
    appId: '1:153311154391:ios:3adb6b492c301c3fece092',
    messagingSenderId: '153311154391',
    projectId: 'blind-assist-66d0d',
    storageBucket: 'blind-assist-66d0d.appspot.com',
    iosClientId: '153311154391-a02lf1bjrcr4atfpuf80d3b5k8ldqvtu.apps.googleusercontent.com',
    iosBundleId: 'com.example.blindAssist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbSMlcUCcjARwu8KgZJQ4gm3ocq13d9L8',
    appId: '1:153311154391:ios:81536098229e6b3eece092',
    messagingSenderId: '153311154391',
    projectId: 'blind-assist-66d0d',
    storageBucket: 'blind-assist-66d0d.appspot.com',
    iosClientId: '153311154391-au81p3lh9odg7ek0o8eg0u4pfjpl3m10.apps.googleusercontent.com',
    iosBundleId: 'com.example.blindAssist.RunnerTests',
  );
}
